### ISSUE TITLE
有报错哦，请问是不是漏提交了zip文件？

### ISSUE THREAD

**Issue by qiuchangjie** [noodle1983/UnityAndroidIl2cppPatchDemo#1]
IOException: Failed to Copy File / Directory from 'E:/unity_update_resolution/UnityAndroidIl2cppPatchDemo/Assets/AndroidIl2cppPatchDemo/PrebuiltPatches/AllAndroidPatchFiles_Version1.zip' to 'E:/unity_update_resolution/UnityAndroidIl2cppPatchDemo/AndroidGradleProject/Test/src/main/assets/AllAndroidPatchFiles_Version1.zip'.

**Comment by noodle1983** [comment]
貌似是的， 先自己build吧
主菜单AndroidBuilder下还提供了菜单“Running Step 1, 2, 4, 5 for the base version”，这是一键构建母包版本用的，母包不需要制作patch文件，所以少了过程3；和菜单“Runnnig Step 1-4 for patch versions”，这是一键构建Patch用的，因为在demo里，不需要导出Apk文件。

**Comment by noodle1983** [comment]
今天想加， 发现这文件比较大， 不适合加进版本管理里。 
原来应该是故意没加
