### ISSUE TITLE
覆盖安装最新版本之后，依然指向之前热更过的旧版本

### ISSUE THREAD

**Issue by 411411qq** [noodle1983/UnityAndroidIl2cppPatchDemo#23]
覆盖安装最新版本之后，依然指向之前热更过的旧版本，比如之前从101版本热更到102版本，后来发布了103版本，然后覆盖安装，运行起来还是在跑102版本，请问这个问题要怎么解决？

**Comment by noodle1983** [comment]
如果检测到覆盖安装， 不会走patch逻辑，以apk版本为准，重走一遍检查patch逻辑
相关检查逻辑在这里， 自己根据需要改
https://github.com/noodle1983/UnityAndroidIl2cppPatchDemo-libboostrap/blob/7594c4d715a655460ec4801c1e7ef175f6139616/bootstrap.cpp#L330

**Comment by noodle1983** [comment]
覆盖安装的apk名可能会不一样， 可能会走到这里
https://github.com/noodle1983/UnityAndroidIl2cppPatchDemo-libboostrap/blob/7594c4d715a655460ec4801c1e7ef175f6139616/bootstrap.cpp#L323

**Comment by 411411qq** [comment]
好的，感谢
