### ISSUE TITLE
AndroidBuilder Step 6 build不出apk

### ISSUE THREAD

**Issue by bightw49986** [noodle1983/UnityAndroidIl2cppPatchDemo#32]
分支：2022_3_base
操作步驟：工具列AndroidBuilder-> Run Step 1-6
第五步的GenrateBuildScript時曾經碰到另一條issue所說的，gen_key.bat生成失敗的問題，同樣透過手動操作解決，但在下一步的時候build不出apk。

從log看起來，可疑的部分有這個，expection while marshalling SDK底下的package.xml(查看該路徑是沒有這個檔案)
![image](https://github.com/user-attachments/assets/32b33d91-761d-410f-8669-cb80e52eab8a)

但接著一直進行到build IL2CPP的步驟都是沒問題的，build node也都是successful
![image](https://github.com/user-attachments/assets/cbaa3b9c-543f-47d2-a07c-9d3e0ddd4979)

到了要把launcher-release.apk複製到cn.noodle1983.unitypatchdemo.apk這步時，出現了The system cannot find the path specified.
![image](https://github.com/user-attachments/assets/06578f68-d240-43d8-a585-e667c5f82e1e)

最後跳出apk not found的error:
![image](https://github.com/user-attachments/assets/8fac791c-2184-4f4d-8f98-adf21d3f2dc1)

再煩請大大協助可能的排除方法

**Comment by noodle1983** [comment]
打包环境问题是第一道门槛，自己调试解决哈。
各自环境千差万别，windows自己不同版本运行起来都有差异，我只能保证我的环境能Build出来，其他的不是什么大问题
