### ISSUE TITLE
2017.4.29. ZipOutputStream Unity里面编译不过

### ISSUE THREAD

**Issue by wylionheart** [noodle1983/UnityAndroidIl2cppPatchDemo#7]
271121
![image](https://user-images.githubusercontent.com/20119767/65032372-98d4e180-d975-11e9-85d6-506a18394797.png)
Assets/AndroidIl2cppPatchDemo/ZipLibrary/ZipHelper.cs(113,54): error CS0012: The type `System.IO.Stream' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
大神，我在2019下面是的对。2017就编译不过了。

**Comment by wylionheart** [comment]
有人吗：）大神快出现：）

**Comment by wylionheart** [comment]
已解决

**Comment by noodle1983** [comment]
才看到， 看看库的历史，2017得还原上一个版本
